package src;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_TYPE = 32;
  public static final int DIVIDE = 5;
  public static final int LBRACKET = 38;
  public static final int POT = 6;
  public static final int CHAR = 21;
  public static final int UMINUS = 52;
  public static final int CASE = 24;
  public static final int SUBTRACT = 3;
  public static final int BACKSLASH = 37;
  public static final int INTEGER = 30;
  public static final int GREATER = 48;
  public static final int LPAREN = 7;
  public static final int INT = 18;
  public static final int LESS = 49;
  public static final int UNDER_LINE = 29;
  public static final int WHERE = 28;
  public static final int BAR = 12;
  public static final int RPAREN = 8;
  public static final int AND = 46;
  public static final int NOT = 45;
  public static final int SEMICOLON = 34;
  public static final int OR = 47;
  public static final int IN = 25;
  public static final int BOOL = 20;
  public static final int COMMA = 13;
  public static final int EQUALEQUAL = 50;
  public static final int DOTDOT = 43;
  public static final int LESS_EQUAL = 11;
  public static final int MULTIPLY = 4;
  public static final int IF = 15;
  public static final int ID = 35;
  public static final int OF = 27;
  public static final int CRASIS = 14;
  public static final int EOF = 0;
  public static final int RBRACKET = 39;
  public static final int EQUAL = 9;
  public static final int TRUE = 22;
  public static final int GREATER_EQUAL = 10;
  public static final int error = 1;
  public static final int DIF = 51;
  public static final int LEFT_ARROW = 42;
  public static final int ADD = 2;
  public static final int TIL = 54;
  public static final int COLON = 33;
  public static final int LBRACE = 40;
  public static final int ELSE = 17;
  public static final int TYPE_STRING = 53;
  public static final int VARSYM = 36;
  public static final int LET = 26;
  public static final int FLOAT = 19;
  public static final int RBRACE = 41;
  public static final int THEN = 16;
  public static final int STRING = 44;
  public static final int FALSE = 23;
  public static final int FLOAT_TYPE = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ADD",
  "SUBTRACT",
  "MULTIPLY",
  "DIVIDE",
  "POT",
  "LPAREN",
  "RPAREN",
  "EQUAL",
  "GREATER_EQUAL",
  "LESS_EQUAL",
  "BAR",
  "COMMA",
  "CRASIS",
  "IF",
  "THEN",
  "ELSE",
  "INT",
  "FLOAT",
  "BOOL",
  "CHAR",
  "TRUE",
  "FALSE",
  "CASE",
  "IN",
  "LET",
  "OF",
  "WHERE",
  "UNDER_LINE",
  "INTEGER",
  "FLOAT_TYPE",
  "CHAR_TYPE",
  "COLON",
  "SEMICOLON",
  "ID",
  "VARSYM",
  "BACKSLASH",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "LEFT_ARROW",
  "DOTDOT",
  "STRING",
  "NOT",
  "AND",
  "OR",
  "GREATER",
  "LESS",
  "EQUALEQUAL",
  "DIF",
  "UMINUS",
  "TYPE_STRING",
  "TIL"
  };
}

